### PR TITLE
Merging parsed and converted trees in ConvertPhase

### PR DESCRIPTION
**Pull request by mdemarne**
This allows the ConvertPhase of the compiler plugin to associate trees parsed by ScalaMeta with semantic information acquired after the typer phase. This is done by merging a converted tree (from scala trees - containing semantic information) and the tree parsed from the source code (containing tokens, positions and sources).

Some minor differences in trees have lead to special cases. In general the format of the parsed tree prevails on the converted one.

### CODE REVIEW

**Comment by xeno-by** [comment]
I'm currently preparing to present at flatMap, so probably won't have time to review this until I get back (next Thursday). Is this going to be a blocker for you?

**Comment by mdemarne** [comment]
No it's fine, I am working with my local version, no problem! :)

**Comment by mdemarne** [comment]
There are some corner cases that probably need to be addressed here. I have been running Obey on large projects (Leon and some Play applications), and this generates warnings due to differences in trees. This is something that needs to be checked before this gets accepted.

Also, with this modified version of scalahost, every compiled source file get parsed by the scalameta Parsers. This seems to generate a few errors. I am not sure yet if this is due to a wrong manipulation on my side or an error in the Parsers: https://gist.github.com/mdemarne/9e45da322390361c9c58.

**Comment by mdemarne** [comment]
@xeno-by:
- Logic to merge trees is now isolated
- Forcing copying of tokens, as they are inferred o/w
- Converted semantic tree added as `scalametaSemantic` metadata
- Parsed/merged tree added as `scalametaSyntactic` metadata

NOTE: this will call `InferToken`, which therefore needs to be implemented. A
temporary hack will be required or we will have to wait for the inference to
be fully implemented - that case this pull request should not be merged
immediately. I am fine with either solution.

**Comment by xeno-by** [comment]
How about we replace the body of `inferTokens.apply` with `Tokens()`, and then this thing will stop crashing?

**Comment by mdemarne** [comment]
This will work fine! Should I do a pull request or do you replace it directly?

**Comment by xeno-by** [comment]
I will, don't worry!

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalahost/pull/93

**Pull request merged**
